---
apiVersion: v1
kind: Service
metadata:
  name: lab10-svc
  labels:
    app: web 
spec:
  type: NodePort
  ports:
  - port: 4000 
    nodePort: 31000
  selector:                                                                                                            
    app: web
