- hosts: masters
#  become: yes
  tasks:
    - name: initialize the cluster
      become: yes
#      become_method: sudo 
#      become_user: root
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.102 >> cluster_initialized.txt 
#      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.102 
      args:
        chdir: /home/dibs 
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: dibs 
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: yes 
#      become_method: sudo 
#      become_user: root 
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/dibs/.kube/config 
        remote_src: yes 
        owner: dibs

    - name: install Pod network
      become: yes 
      become_user: dibs 
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
